// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("ipcrypt", os.Args, []testing.Test{
		{Name: "TestDeterministicVectors", F: TestDeterministicVectors},
		{Name: "TestNDVectors", F: TestNDVectors},
		{Name: "TestNDXVectors", F: TestNDXVectors},
		{Name: "TestPfxVectors", F: TestPfxVectors},
		{Name: "TestPfxPreservesPrefix", F: TestPfxPreservesPrefix},
		{Name: "TestRandomTweak", F: TestRandomTweak},
		{Name: "TestKiasuBC", F: TestKiasuBC},
		{Name: "TestInvalidInputs", F: TestInvalidInputs},
		{Name: "TestUninitializedCiphers", F: TestUninitializedCiphers},
		{Name: "TestRandomRoundTrips", F: TestRandomRoundTrips},
	})
}
